
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command:
      - "app.py"
    ports:
      - "5000:5000"
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"